Support to EO IAM

diff --git a/secp b/secp
--- a/secp
+++ b/secp
@@ -3,13 +3,14 @@
 # Outline:
 #   secp is a generic utility to perform bulk downloads to a sink directory.
 #   Its features are:
-#     * Parallel downloads (optionally with multiple credentials)
-#     * Support for ftp, scp, http, https, gridftp, hadoopfs, file and nfs.
-#     * Support for basic, ESA's EO-SSO and EO Data Gateway authentication
-#     * Credentials and session manager
-#     * Automatic unpackaging of files
-#     * Support for file lists in metalink, ATOM (@rel=enclosure), RDF, HTML
-#       (meta-refresh and href-tags), UAR (url textual file lists)
+#       * Download from most of the ESA data archives and catalogues (SciHub, OADS, SMOS, VA4, ESAR, MERCI, etc...)
+#       * Parallel downloads (optionally with multiple credentials)
+#       * Support for ftp, scp, http, https, gridftp, hadoopfs, file and nfs.
+#       * Support for HTTP/FTP basic auth (e.g. SciHub), ESA's EO-SSO, IAM and EO Data Gateway authentication
+#       * Support for basic, ESA's EO-SSO, IAM and EO Data Gateway authentication
+#       * Credentials and session manager
+#       * Automatic unpackaging of files
+#       * Support for file lists in metalink, ATOM (@rel=enclosure), RDF, HTML, (meta-refresh and href-tags), UAR (url textual file lists)
 #
 # Dependencies: curl, scp, gawk, sed, bash, sha256sum, file, globus-url-copy [optional]
 # 
@@ -112,6 +113,8 @@
 #       * added compatibility with dos filelists
 #       * fix bug on handling remote file lists (uses now the file command to determine the type of remote file)
 #       * added functionality to access files with HTTP POST
+# version 3.2.3
+#       * added support for ESA EO IAM (Earth Observation Identity and Access Management System
 #
 # License:
 #  This program is free software: you can redistribute it and/or modify
@@ -127,7 +130,7 @@
 #  You should have received a copy of the GNU General Public License
 #  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #
-SECP_VERSION=3.2.2
+SECP_VERSION=3.2.3
 
 # Usage:
 function usage {
@@ -194,7 +197,7 @@ Notes:
  *  Unless the -H options is specified, the software will follow Metalink, ATOM, RDF, HTML (href) and uar
     pages. the software will also follow HTTP meta-refresh and XML Retry-After tags
  *  The software will perform authentication if credentials are specified. Supported authentication types
-    are 'basic', X509, EO-SSO and EO Data gateway. Credentials are stored in the ~/.secp_cred file, session
+    are 'basic', X509, ESA's EO-SSO, IAM and EO Data gateway. Credentials are stored in the ~/.secp_cred file, session
     cookies are stored in the ~/.secp_sess file (use -K switch to disable this behaviour)
  *  If the url is an HTTP url, everyhting after the special '|' caracter will be sent via an HTTP POST
 
@@ -203,6 +206,8 @@ Advanced usage examples:
      ./secp -J -co outdir -P 2 -F 'https://scihub.copernicus.eu/dhus/search?q=*&rows=5&start=0'
   * Download the SMOS L2 products from 2016-09-01 to 2016-09-30
      ./secp -U -F 'https://smos-diss.eo.esa.int/socat/NRT_Open/search|service=SimpleOnlineCatalogue&version=1.0&request=search&format=text%2Fplain&pageCount=50&query.beginAcquisition.start=2016-09-01&query.beginAcquisition.stop=2016-09-30&query.productType=MIR_SMNRT2'
+  * Download a product from OADS
+     ./secp 'https://eoiam-oads.eo.esa.int/oads/data/RapidEye_SouthAmerica/RE__OPER_MSI_IMG_3A_20150727T143335_S25-908_W054-484_4140.SIP.ZIP'
 
 Exit codes:
       0      all URLs were successfully downloaded
@@ -914,6 +919,51 @@ while [[ -n "$_INPUT_URI" ]]; do
         echo "[ERROR  ][secp][auth] Failed to login into EO-SSO. Please check your authentication credentials." 1>&2
         eval "$ON_ERROR"
       fi
+    elif grep -q '<title>Earth Observation Identity and Access Management System</title>' $_LOCAL_FILE; then
+      #This seems to be the EO IAM login page, perform login
+      echo '[INFO   ][secp][auth] EO IAM login page detected. Logging in and re-downloading the file...'
+
+      #Check if the page version and other pre-requisites
+      SSO_SESSKEY="`sed -n 's/.*<input type="hidden" name="sessionDataKey" value='\''\(.*\)'\''\/.*>/\1/p' $_LOCAL_FILE`"
+      if [[ -z "$SSO_SESSKEY" ]]; then
+        echo "[ERROR  ][secp][auth] EO IAM page invalid. Missing session key." 1>&2
+        eval "$ON_ERROR"
+      fi
+      IDP_ADDR="`sed -n 's|^.*<a *id="usernameRecoverLink" *href="\(.*\)/accountrecoveryendpoint/.*$|\1|p' $_LOCAL_FILE`/samlsso"
+      if [[ "$IDP_ADDR" == "/samlsso" ]]; then
+        echo "[ERROR  ][secp][auth] EO IAM page invalid. Missing idp address." 1>&2
+        eval "$ON_ERROR"
+      fi
+      if [[ $_SESSION_FILE == "/dev/null" || ! -w $_SESSION_FILE ]]; then
+        echo "[ERROR  ][secp][auth] You need to enable session file to perform EO IAM login." 1>&2
+        eval "$ON_ERROR"
+      fi
+
+      #Load EO IAM password (this is mandatory)
+      SSO_SERVER=${IDP_ADDR#*://}; SSO_SERVER=${SSO_SERVER%%:*}; SSO_SERVER=${SSO_SERVER%%/*};
+      loadpass "$SSO_SERVER" true
+
+      #Try to perform login
+      curl -b $_SESSION_FILE -c $_SESSION_FILE -L -k -f -s -S "$IDP_ADDR" --data "tocommonauth=true&username=$_SERVER_USERNAME&password=$_SERVER_PASSWORD&sessionDataKey=$SSO_SESSKEY" -o $_LOCAL_FILE
+      if [[ $? -ne 0 ]]; then
+        echo "[ERROR  ][secp][auth] Failed to login into EO IAM. Cannot connect to the server." 1>&2
+        eval "$ON_ERROR"
+      fi
+      if grep -q '<title>Earth Observation Identity and Access Management System</title>' $_LOCAL_FILE; then
+        echo "[ERROR  ][secp][auth] Failed to login into EO IAM. Please check your authentication credentials." 1>&2
+        eval "$ON_ERROR"
+      fi
+
+      #Redirect to IDP
+      REDIR_ADDR="`sed -n 's|^.*<form method='\''post'\'' action='\''\([^'\'']*\)'\''>.*$|\1|p' $_LOCAL_FILE`"
+      REDIR_DATA="`gawk 'BEGIN{RS="<|>";FS="  *|'\''";for (i = 0; i <= 255; i++) {ord[sprintf("%c", i)] = i}}function escape(str, c, len, res) {len = length(str);res = "";for (i = 1; i <= len; i++){c = substr(str, i, 1);if (c ~ /[0-9A-Za-z]/){res = res c}else{res = res "%" sprintf("%02X", ord[c])}}return res}{if($1=="input"){for(i=2;i<NF;i++){if($i~/^name/){i++;while($i=="")i++;nm=$i}};for(i=2;i<NF;i++){if($i~/^value/){i++;while($i=="")i++;val=$i}};if(t==0){t=1}else{printf "&"}printf nm"="escape(val)}}' $_LOCAL_FILE`"
+      if [[ -z "$REDIR_ADDR" || -z "$REDIR_DATA" ]]; then
+        echo "[ERROR  ][secp][auth] Failed to login into EO IAM. Invalid response received." 1>&2
+        eval "$ON_ERROR"
+      fi
+      curl -b $_SESSION_FILE -c $_SESSION_FILE -L -k -f -s -S "$REDR_ADDR" --data "$REDIR_DATA" -o $_LOCAL_FILE
+      res=$?
+
     elif grep -q 'login.php?rediurl=' $_LOCAL_FILE; then
       #This seems to be an internal EO data gateway login page, perform EO Data Gateway internal login
       echo "[INFO   ][secp][auth] EO Data Gateway login page detected. Logging in and re-downloading the file..." 1>&2
